FORMAT_FOLDER?='/home/pavlin/workarea/TMS/Homework/TMS_hw/hw_lesson 24/online_shop/'

format:
	make black FORMAT_FOLDER=${FORMAT_FOLDER}
	make isort FORMAT_FOLDER=${FORMAT_FOLDER}
	make flake8 FORMAT_FOLDER=${FORMAT_FOLDER}
	make interrogate FORMAT_FOLDER=${FORMAT_FOLDER}