# Generated by Django 4.1.5 on 2023-01-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='data_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
