# Generated by Django 4.1.5 on 2023-01-10 11:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_posts_data_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=60, validators=[django.core.validators.EmailValidator(message='Введите корректный email')]),
        ),
        migrations.AlterField(
            model_name='users',
            name='login',
            field=models.CharField(max_length=60, validators=[django.core.validators.RegexValidator(message='Введите корректный login', regex='^\\b\\w{6,10}\\b$')]),
        ),
    ]
