[tool.isort]
skip = [".gitignore", ".dockerignore", "venv", ".venv"]

[tool.flake8]
# не работает
ignore = ['E203', 'E266', 'E501', 'W503', 'F403', 'F401']
#ignore = """E203, E266, E501, W503, F403, F401"""
#ignore = E203, E266, E501, W503, F403, F401
max-line-length = 120

[tool.interrogate]
ignore-init-method = true
ignore-init-module = true
ignore-magic = false
ignore-semiprivate = false
ignore-private = false
ignore-property-decorators = false
ignore-module = true
ignore-nested-functions = false
ignore-nested-classes = true
ignore-setters = false
fail-under = 95
exclude = ["travel_service/users/migrations", "travel_service/booking/migrations"]
