# Generated by Django 4.1.7 on 2023-04-03 10:12

import booking.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Direction Name')),
                ('slug', models.SlugField(max_length=70, verbose_name='Short Name')),
                ('start_point', models.CharField(max_length=40, verbose_name='Where does the route start')),
                ('end_point', models.CharField(max_length=40, verbose_name='Where does the route end?')),
                ('direction_date', models.DateField(verbose_name='Date of all trips')),
            ],
            options={
                'verbose_name': 'Direction',
                'verbose_name_plural': 'Directions',
            },
        ),
        migrations.CreateModel(
            name='DateRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_route', models.DateField(verbose_name='Date of trip')),
                ('slug', models.SlugField(max_length=30, verbose_name='Short DateName')),
                ('amount_trips', models.IntegerField(default=0, verbose_name='Trips Amount In Date')),
                ('direction_name', models.ForeignKey(default=booking.models.Direction.get_default_direction_pk, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='booking.direction', verbose_name='Direction Name')),
            ],
            options={
                'verbose_name': 'DateRoute',
                'verbose_name_plural': 'DateRoutes',
            },
        ),
    ]
