# Generated by Django 4.1.7 on 2023-04-07 16:33

import booking.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DateRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is it active?')),
                ('date_route', models.DateField(verbose_name='Date of trip')),
            ],
            options={
                'verbose_name': 'DateRoute',
                'verbose_name_plural': 'DateRoutes',
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is it active?')),
                ('slug', models.SlugField(max_length=70, verbose_name='Short Name')),
                ('name', models.CharField(max_length=70, verbose_name='Direction Name')),
                ('start_point', models.CharField(max_length=40, verbose_name='Where does the route start?')),
                ('end_point', models.CharField(max_length=40, verbose_name='Where does the route end?')),
                ('list_of_stops', models.CharField(default='Rest.1, Rest.2', max_length=200, verbose_name='Enter stops separated by commas.(For example: Rest.1, Rest.2)')),
                ('travel_time', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Travel time in minutes')),
            ],
            options={
                'verbose_name': 'Direction',
                'verbose_name_plural': 'Directions',
            },
        ),
        migrations.CreateModel(
            name='TimeTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.TimeField(verbose_name='Departure time')),
                ('car', models.CharField(default='Mercedes-Benz Sprinter', max_length=80, verbose_name='Car Name')),
                ('auto_number', models.CharField(default='1234AB-7', max_length=10, verbose_name='Auto Number')),
                ('carrier_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('number_of_seats', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of seats')),
                ('price', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Price per seats')),
                ('date_of_the_trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.dateroute', verbose_name='Travel date')),
                ('direction', models.ForeignKey(default=booking.models.Direction.get_default_direction_pk, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.direction', verbose_name='Travel direction')),
            ],
            options={
                'verbose_name': 'TimeTrip',
                'verbose_name_plural': 'TimeTrips',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_reserved_places', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Reserved places')),
                ('landing_place', models.CharField(choices=[('1', 'Stopping 1'), ('2', 'Stopping 2'), ('3', 'Stopping 3'), ('4', 'Stopping 4'), ('5', 'Stopping 5')], max_length=300, verbose_name='Landing place')),
                ('user_comment', models.CharField(default='nothing', max_length=200, null=True, verbose_name='User Comment')),
                ('date_of_the_trip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.dateroute', verbose_name='Trip date')),
                ('departure_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.timetrip', verbose_name='Departure time')),
                ('user_phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User phone')),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
            },
        ),
        migrations.AddField(
            model_name='dateroute',
            name='direction_name',
            field=models.ManyToManyField(to='booking.direction', verbose_name='Direction Name'),
        ),
    ]
