# Generated by Django 4.1.7 on 2023-04-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='travel_time',
            field=models.IntegerField(default=0, verbose_name='Travel time in minutes'),
        ),
    ]
