# Generated by Django 4.1.7 on 2023-04-03 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_direction_travel_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direction',
            name='direction_date',
        ),
    ]
