# Generated by Django 4.1.7 on 2023-04-22 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("booking", "0002_remove_trip_user_phone_trip_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="username",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User name",
            ),
        ),
    ]
