# Generated by Django 4.1.7 on 2023-04-03 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_direction_direction_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.TimeField(verbose_name='Departure time')),
                ('arrival_time', models.TimeField(verbose_name='Arrival time')),
                ('carrier', models.CharField(max_length=80, verbose_name='Carrier Name')),
                ('number_of_seats', models.IntegerField(default=0, verbose_name='Number of seats')),
                ('date_of_the_trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.dateroute', verbose_name='Travel date')),
            ],
            options={
                'verbose_name': 'TimeTrip',
                'verbose_name_plural': 'TimeTrips',
            },
        ),
    ]
