# Generated by Django 4.1.7 on 2023-04-03 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_timetrip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetrip',
            name='arrival_time',
        ),
    ]
