# Generated by Django 4.1.7 on 2023-04-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0004_alter_trip_user_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="user_comment",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="User Comment"
            ),
        ),
    ]
