# Generated by Django 4.1.7 on 2023-04-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_timetrip_arrival_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetrip',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Price per seats'),
        ),
    ]
