# Generated by Django 4.1.7 on 2023-04-03 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0006_timetrip_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dateroute',
            name='amount_trips',
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_reserved_places', models.IntegerField(default=0, verbose_name='Reserved places')),
                ('landing_place', models.CharField(max_length=70, verbose_name='Landing place')),
                ('departure_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.timetrip', verbose_name='Departure time')),
                ('user_phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User phone')),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
            },
        ),
    ]
