# Generated by Django 4.1.7 on 2023-04-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0007_alter_trip_user_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="landing_place",
            field=models.CharField(
                choices=[
                    ("1", "Ост. 1"),
                    ("2", "Ост. 2"),
                    ("3", "Ост. 3"),
                    ("4", "Ост. 4"),
                    ("5", "Ост. 5"),
                ],
                max_length=300,
                verbose_name="Landing place",
            ),
        ),
    ]
