# Generated by Django 4.1.7 on 2023-04-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_remove_dateroute_amount_trips_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='dateroute',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is it active?'),
        ),
        migrations.AddField(
            model_name='direction',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is it active?'),
        ),
        migrations.AlterField(
            model_name='dateroute',
            name='slug',
            field=models.SlugField(max_length=70, verbose_name='Short Name'),
        ),
    ]
