# Generated by Django 4.2 on 2023-04-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0008_alter_trip_landing_place"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="user_trip_ticket",
            field=models.FileField(
                blank=True, null=True, upload_to="booking/% Y/% m/% d/"
            ),
        ),
    ]
