# Generated by Django 4.1.7 on 2023-04-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_dateroute_is_active_direction_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetrip',
            name='auto_number',
            field=models.CharField(default='1234AB-7', max_length=10, verbose_name='Auto Number'),
        ),
    ]
