# Generated by Django 4.1.7 on 2023-04-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_timetrip_auto_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dateroute',
            name='direction_name',
        ),
        migrations.AddField(
            model_name='dateroute',
            name='direction_name',
            field=models.ManyToManyField(to='booking.direction', verbose_name='Direction Name'),
        ),
    ]
