# Generated by Django 4.1.7 on 2023-04-05 09:37

import booking.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_remove_dateroute_direction_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetrip',
            name='direction',
            field=models.ForeignKey(default=booking.models.Direction.get_default_direction_pk, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.direction', verbose_name='Travel direction'),
        ),
        migrations.AddField(
            model_name='timetrip',
            name='car',
            field=models.CharField(default='Mercedes-Benz Sprinter', max_length=80, verbose_name='Car Name'),
        ),
        migrations.RemoveField(
            model_name='timetrip',
            name='carrier',
        ),
    ]
