# Generated by Django 4.2 on 2023-05-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0010_log_alter_trip_user_trip_ticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetrip",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is it active?"),
        ),
    ]
