# Generated by Django 4.1.7 on 2023-04-05 12:48

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_timetrip_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetrip',
            name='carrier_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+375441111111', max_length=128, region=None),
        ),

    ]
