# Generated by Django 4.1.7 on 2023-04-05 12:48

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_timetrip_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetrip',
            name='carrier_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+375441111111', max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='direction',
            name='list_of_stops',
            field=models.CharField(default='Rest.1, Rest.2', max_length=200,
                                   verbose_name='Enter stops separated by commas.(For example: Rest.1, Rest.2)'),
        ),
    ]
