# Generated by Django 4.1.7 on 2023-04-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_remove_timetrip_carrier_timetrip_carrier_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='landing_place',
            field=models.CharField(choices=[], max_length=300, verbose_name='Landing place'),
        ),
    ]
