# Generated by Django 4.1.7 on 2023-04-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_direction_list_of_stops_alter_trip_landing_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='user_comment',
            field=models.CharField(max_length=200, verbose_name='User Comment', default='nothing'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='landing_place',
            field=models.CharField(choices=[('1', 'Stopping 1'), ('2', 'Stopping 2'), ('3', 'Stopping 3'), ('4', 'Stopping 4'), ('5', 'Stopping 5')], max_length=300, verbose_name='Landing place'),
        ),
    ]
