# Generated by Django 4.1.7 on 2023-04-05 14:52

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_trip_user_comment_alter_trip_landing_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetrip',
            name='carrier_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
