# Generated by Django 4.1.7 on 2023-04-07 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_alter_timetrip_carrier_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='date_of_the_trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.dateroute', verbose_name='Trip date'),
        ),
    ]
