# Generated by Django 4.1.7 on 2023-04-07 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_trip_date_of_the_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dateroute',
            name='slug',
        ),
    ]
