# Generated by Django 4.1.7 on 2023-04-07 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_remove_dateroute_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dateroute',
            old_name='data_route',
            new_name='date_route',
        ),
    ]
