# Generated by Django 4.1.7 on 2023-04-10 14:25

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookinguser",
            name="carrier_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, null=True, region=None
            ),
        ),
        migrations.AddField(
            model_name="bookinguser",
            name="date_of_birth",
            field=models.DateTimeField(null=True, verbose_name="Date of birth"),
        ),
    ]
