# Generated by Django 4.1.7 on 2023-04-11 14:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_bookinguser_carrier_phone_bookinguser_date_of_birth"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookinguser",
            old_name="carrier_phone",
            new_name="phone",
        ),
    ]
