# Generated by Django 4.1.7 on 2023-04-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_carrier_phone_bookinguser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinguser',
            name='cookie_consent',
            field=models.BooleanField(default=True, verbose_name='Do you agree to the use of cookies?'),
        ),
    ]
