# Generated by Django 4.1.7 on 2023-04-23 18:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_bookinguser_cookie_consent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookinguser",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
    ]
