# Generated by Django 4.2 on 2023-05-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_bookinguser_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookinguser",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                unique=True,
                verbose_name="Email address",
            ),
        ),
    ]
