# Generated by Django 4.2 on 2023-05-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_bookinguser_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookinguser",
            name="date_of_birth",
            field=models.DateField(null=True, verbose_name="Date of birth"),
        ),
    ]
