# Generated by Django 4.1.5 on 2023-01-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=50, verbose_name="Category Title"),
                ),
                ("slug", models.CharField(max_length=20, verbose_name="Category Slug")),
                (
                    "description",
                    models.CharField(
                        max_length=140, verbose_name="Category Description"
                    ),
                ),
                ("is_active", models.BooleanField(verbose_name="Category is active?")),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
    ]
