# Generated by Django 4.1.5 on 2023-01-18 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Game Name")),
                (
                    "pub_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Published date"
                    ),
                ),
                (
                    "release_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Release date"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        max_length=4,
                        verbose_name="Game Price",
                    ),
                ),
                ("slug", models.CharField(max_length=20, verbose_name="Game Slug")),
                (
                    "description",
                    models.CharField(max_length=140, verbose_name="Game Description"),
                ),
                (
                    "game_image",
                    models.ImageField(
                        upload_to="photos/%Y/%m/%d/", verbose_name="Game Image"
                    ),
                ),
                ("is_active", models.BooleanField(verbose_name="Game is active?")),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shop.category",
                        verbose_name="Game Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Name",
                "verbose_name_plural": "Names",
            },
        ),
    ]
