# Generated by Django 4.1.5 on 2023-01-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_alter_game_options_alter_category_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="release_date",
            field=models.DateTimeField(verbose_name="Release date"),
        ),
    ]
