# Generated by Django 4.1.5 on 2023-01-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_alter_game_release_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(max_length=20, verbose_name="Category Slug"),
        ),
        migrations.AlterField(
            model_name="game",
            name="slug",
            field=models.SlugField(max_length=20, verbose_name="Game Slug"),
        ),
    ]
