# Generated by Django 4.1.5 on 2023-01-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_game_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='games_amount',
            field=models.IntegerField(default=0, verbose_name='Games Amount In Category'),
        ),
    ]
