# Generated by Django 4.1.5 on 2023-02-05 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0014_alter_category_description_alter_game_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=100, verbose_name="Comment text")),
                (
                    "pub_date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Comment publication date"
                    ),
                ),
                ("rating", models.IntegerField(verbose_name="Comment rating")),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.game"
                    ),
                ),
            ],
        ),
    ]
