# Generated by Django 4.1.5 on 2023-03-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0017_alter_comment_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=300, verbose_name="request path")),
                ("user", models.CharField(max_length=100, verbose_name="request user")),
                (
                    "datetime",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Response datetime"
                    ),
                ),
            ],
        ),
    ]
