# Generated by Django 4.1.5 on 2023-03-13 09:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0018_log"),
    ]

    operations = [
        migrations.RenameField(
            model_name="log",
            old_name="datetime",
            new_name="log_datetime",
        ),
        migrations.RenameField(
            model_name="log",
            old_name="path",
            new_name="log_path",
        ),
        migrations.RenameField(
            model_name="log",
            old_name="user",
            new_name="log_user",
        ),
    ]
