# Generated by Django 4.1.5 on 2023-03-19 11:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0020_basket"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basket",
            name="quantity",
        ),
    ]
